-- ============================================================
-- FILE: 01_sequences.sql
-- MUC DICH: Tao tat ca SEQUENCES cho he thong quan ly hoat dong tinh nguyen
-- CHAY TRUOC: Tat ca cac file khac
-- ============================================================

-- Xoa sequence cu neu ton tai (bo qua loi neu khong ton tai)
BEGIN
    FOR s IN (SELECT sequence_name FROM user_sequences 
              WHERE sequence_name IN (
                'S_TAIKHOAN_ID','S_HOSO_ID','S_NHATKY_ID','S_CHIENDICH_ID',
                'S_DUYET_ID','S_TINTUC_ID','S_BINHLUAN_ID','S_THAMGIA_ID',
                'S_CONGVIEC_ID','S_PHANCONG_ID','S_DIEMDANH_ID',
                'S_MINHCHUNGTNV_ID','S_MINHCHUNGCT_ID','S_GIAYCHUNGNHAN_ID',
                'S_QUYENGOP_ID','S_THANHTOAN_ID','S_CHITIEU_ID',
                'S_DOITAC_ID','S_TAITRO_ID','S_LOAIVP_ID',
                'S_PHIEUQGVP_ID','S_PHIEUXUAT_ID','S_THONGBAO_ID','S_THAMSO_ID'
              )) LOOP
        EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
    END LOOP;
END;
/

-- ============================================================
-- SEQUENCES CHINH
-- ============================================================

CREATE SEQUENCE s_taikhoan_id
    MINVALUE 1 MAXVALUE 9999999
    INCREMENT BY 1 START WITH 1
    NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE s_hoso_id
    MINVALUE 1 MAXVALUE 9999999
    INCREMENT BY 1 START WITH 1
    NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE s_nhatky_id
    MINVALUE 1 MAXVALUE 9999999
    INCREMENT BY 1 START WITH 1
    NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE s_chiendich_id
    MINVALUE 1 MAXVALUE 9999999
    INCREMENT BY 1 START WITH 1
    NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE s_duyet_id
    MINVALUE 1 MAXVALUE 9999999
    INCREMENT BY 1 START WITH 1
    NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE s_tintuc_id
    MINVALUE 1 MAXVALUE 9999999
    INCREMENT BY 1 START WITH 1
    NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE s_binhluan_id
    MINVALUE 1 MAXVALUE 9999999
    INCREMENT BY 1 START WITH 1
    NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE s_thamgia_id
    MINVALUE 1 MAXVALUE 9999999
    INCREMENT BY 1 START WITH 1
    NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE s_congviec_id
    MINVALUE 1 MAXVALUE 9999999
    INCREMENT BY 1 START WITH 1
    NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE s_phancong_id
    MINVALUE 1 MAXVALUE 9999999
    INCREMENT BY 1 START WITH 1
    NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE s_diemdanh_id
    MINVALUE 1 MAXVALUE 9999999
    INCREMENT BY 1 START WITH 1
    NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE s_minhchungtnv_id
    MINVALUE 1 MAXVALUE 9999999
    INCREMENT BY 1 START WITH 1
    NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE s_minhchungct_id
    MINVALUE 1 MAXVALUE 9999999
    INCREMENT BY 1 START WITH 1
    NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE s_giaychungnhan_id
    MINVALUE 1 MAXVALUE 9999999
    INCREMENT BY 1 START WITH 1
    NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE s_quyengop_id
    MINVALUE 1 MAXVALUE 9999999
    INCREMENT BY 1 START WITH 1
    NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE s_thanhtoan_id
    MINVALUE 1 MAXVALUE 9999999
    INCREMENT BY 1 START WITH 1
    NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE s_chitieu_id
    MINVALUE 1 MAXVALUE 9999999
    INCREMENT BY 1 START WITH 1
    NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE s_doitac_id
    MINVALUE 1 MAXVALUE 9999999
    INCREMENT BY 1 START WITH 1
    NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE s_taitro_id
    MINVALUE 1 MAXVALUE 9999999
    INCREMENT BY 1 START WITH 1
    NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE s_loaivp_id
    MINVALUE 1 MAXVALUE 9999999
    INCREMENT BY 1 START WITH 1
    NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE s_phieuqgvp_id
    MINVALUE 1 MAXVALUE 9999999
    INCREMENT BY 1 START WITH 1
    NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE s_phieuxuat_id
    MINVALUE 1 MAXVALUE 9999999
    INCREMENT BY 1 START WITH 1
    NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE s_thongbao_id
    MINVALUE 1 MAXVALUE 9999999
    INCREMENT BY 1 START WITH 1
    NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE s_thamso_id
    MINVALUE 1 MAXVALUE 9999999
    INCREMENT BY 1 START WITH 1
    NOCACHE NOORDER NOCYCLE;

COMMIT;
PROMPT >> 01_sequences.sql: Da tao xong tat ca SEQUENCES.
