import express from 'express';
import { getConnection, executeQuery } from '../db.js';

const router = express.Router();
const sessions = new Map();

async function tableExists(tableName) {
  const result = await executeQuery(
    `SELECT COUNT(*) AS CNT FROM USER_TABLES WHERE TABLE_NAME = :tableName`,
    { tableName }
  );
  return Number(result.rows[0]?.CNT || 0) > 0;
}

async function ensureDemoTables() {
  if (!(await tableExists('DEMO_CONCURRENCY_ITEM'))) {
    await executeQuery(`
      CREATE TABLE DEMO_CONCURRENCY_ITEM (
        ID NUMBER PRIMARY KEY,
        TEN VARCHAR2(100),
        GIA_TRI NUMBER,
        NHOM VARCHAR2(50)
      )
    `);
  }

  if (!(await tableExists('DEMO_CONCURRENCY_MEMBER'))) {
    await executeQuery(`
      CREATE TABLE DEMO_CONCURRENCY_MEMBER (
        ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        HO_TEN VARCHAR2(100),
        MA_CHIEN_DICH NUMBER,
        TRANG_THAI VARCHAR2(30)
      )
    `);
  }
}

async function resetDemoData() {
  await ensureDemoTables();
  await executeQuery(`DELETE FROM DEMO_CONCURRENCY_MEMBER`, {}, true);
  await executeQuery(`DELETE FROM DEMO_CONCURRENCY_ITEM`, {}, true);
  await executeQuery(`
    INSERT INTO DEMO_CONCURRENCY_ITEM (ID, TEN, GIA_TRI, NHOM)
    VALUES (1, 'So du chien dich demo', 100, 'BALANCE')
  `, {}, true);
  await executeQuery(`
    INSERT INTO DEMO_CONCURRENCY_ITEM (ID, TEN, GIA_TRI, NHOM)
    VALUES (2, 'Quy dinh so gio toi thieu', 20, 'RULE')
  `, {}, true);
  await executeQuery(`
    INSERT INTO DEMO_CONCURRENCY_ITEM (ID, TEN, GIA_TRI, NHOM)
    VALUES (3, 'Dong khoa A', 10, 'LOCK')
  `, {}, true);
  await executeQuery(`
    INSERT INTO DEMO_CONCURRENCY_ITEM (ID, TEN, GIA_TRI, NHOM)
    VALUES (4, 'Dong khoa B', 30, 'LOCK')
  `, {}, true);
  await executeQuery(`
    INSERT INTO DEMO_CONCURRENCY_MEMBER (HO_TEN, MA_CHIEN_DICH, TRANG_THAI)
    VALUES ('Nguyen Van Demo 1', 1, 'ACTIVE')
  `, {}, true);
  await executeQuery(`
    INSERT INTO DEMO_CONCURRENCY_MEMBER (HO_TEN, MA_CHIEN_DICH, TRANG_THAI)
    VALUES ('Tran Thi Demo 2', 1, 'ACTIVE')
  `, {}, true);
}

async function getSnapshot() {
  const itemResult = await executeQuery(`
    SELECT ID, TEN, GIA_TRI, NHOM
    FROM DEMO_CONCURRENCY_ITEM
    ORDER BY ID
  `);
  const memberResult = await executeQuery(`
    SELECT COUNT(*) AS CNT
    FROM DEMO_CONCURRENCY_MEMBER
    WHERE MA_CHIEN_DICH = 1 AND TRANG_THAI = 'ACTIVE'
  `);
  return {
    items: itemResult.rows,
    activeMembers: Number(memberResult.rows[0]?.CNT || 0)
  };
}

async function closeSession(name) {
  const session = sessions.get(name);
  if (!session) return;
  try {
    await session.connection.rollback();
    await session.connection.close();
  } catch (err) {
    // Ignore cleanup errors so reset never blocks the demo.
  }
  sessions.delete(name);
}

function getSession(name) {
  const session = sessions.get(name);
  if (!session) {
    const error = new Error(`Phiên ${name} chưa được bắt đầu.`);
    error.status = 400;
    throw error;
  }
  return session;
}

router.post('/reset', async (req, res, next) => {
  try {
    await closeSession('s1');
    await closeSession('s2');
    await resetDemoData();
    res.json({
      message: 'Đã khởi tạo lại dữ liệu demo.',
      snapshot: await getSnapshot()
    });
  } catch (err) {
    next(err);
  }
});

router.post('/begin/:session', async (req, res, next) => {
  try {
    const name = req.params.session;
    await closeSession(name);
    const connection = await getConnection();
    sessions.set(name, { connection, reads: {} });
    res.json({ message: `Đã bắt đầu giao tác cho ${name.toUpperCase()}.` });
  } catch (err) {
    next(err);
  }
});

router.post('/rollback/:session', async (req, res, next) => {
  try {
    const name = req.params.session;
    await closeSession(name);
    res.json({
      message: `Đã rollback và đóng ${name.toUpperCase()}.`,
      snapshot: await getSnapshot()
    });
  } catch (err) {
    next(err);
  }
});

router.post('/commit/:session', async (req, res, next) => {
  try {
    const name = req.params.session;
    const session = getSession(name);
    await session.connection.commit();
    await session.connection.close();
    sessions.delete(name);
    res.json({
      message: `Đã commit ${name.toUpperCase()}.`,
      snapshot: await getSnapshot()
    });
  } catch (err) {
    next(err);
  }
});

router.post('/lost-update/read/:session', async (req, res, next) => {
  try {
    const name = req.params.session;
    const session = getSession(name);
    const result = await session.connection.execute(`
      SELECT GIA_TRI
      FROM DEMO_CONCURRENCY_ITEM
      WHERE ID = 1
    `);
    const value = Number(result.rows[0]?.GIA_TRI || 0);
    session.reads.balance = value;
    res.json({ message: `${name.toUpperCase()} đọc số dư = ${value}.`, value });
  } catch (err) {
    next(err);
  }
});

router.post('/lost-update/write/:session', async (req, res, next) => {
  try {
    const name = req.params.session;
    const delta = Number(req.body.delta || 0);
    const session = getSession(name);
    const oldValue = Number(session.reads.balance || 0);
    const newValue = oldValue + delta;
    await session.connection.execute(`
      UPDATE DEMO_CONCURRENCY_ITEM
      SET GIA_TRI = :newValue
      WHERE ID = 1
    `, { newValue });
    res.json({
      message: `${name.toUpperCase()} ghi số dư = ${newValue} dựa trên giá trị đã đọc trước đó (${oldValue}).`
    });
  } catch (err) {
    next(err);
  }
});

router.post('/non-repeatable/read/:session', async (req, res, next) => {
  try {
    const name = req.params.session;
    const session = getSession(name);
    const result = await session.connection.execute(`
      SELECT GIA_TRI
      FROM DEMO_CONCURRENCY_ITEM
      WHERE ID = 2
    `);
    const value = Number(result.rows[0]?.GIA_TRI || 0);
    res.json({ message: `${name.toUpperCase()} đọc quy định số giờ tối thiểu = ${value}.`, value });
  } catch (err) {
    next(err);
  }
});

router.post('/non-repeatable/update/:session', async (req, res, next) => {
  try {
    const name = req.params.session;
    const value = Number(req.body.value || 0);
    const session = getSession(name);
    await session.connection.execute(`
      UPDATE DEMO_CONCURRENCY_ITEM
      SET GIA_TRI = :value
      WHERE ID = 2
    `, { value });
    res.json({ message: `${name.toUpperCase()} cập nhật quy định số giờ tối thiểu thành ${value}.` });
  } catch (err) {
    next(err);
  }
});

router.post('/phantom/count/:session', async (req, res, next) => {
  try {
    const name = req.params.session;
    const session = getSession(name);
    const result = await session.connection.execute(`
      SELECT COUNT(*) AS CNT
      FROM DEMO_CONCURRENCY_MEMBER
      WHERE MA_CHIEN_DICH = 1 AND TRANG_THAI = 'ACTIVE'
    `);
    const count = Number(result.rows[0]?.CNT || 0);
    res.json({ message: `${name.toUpperCase()} đếm được ${count} TNV đang tham gia chiến dịch demo.`, count });
  } catch (err) {
    next(err);
  }
});

router.post('/phantom/insert/:session', async (req, res, next) => {
  try {
    const name = req.params.session;
    const session = getSession(name);
    await session.connection.execute(`
      INSERT INTO DEMO_CONCURRENCY_MEMBER (HO_TEN, MA_CHIEN_DICH, TRANG_THAI)
      VALUES ('Pham Van Phantom', 1, 'ACTIVE')
    `);
    res.json({ message: `${name.toUpperCase()} thêm một TNV mới vào chiến dịch demo.` });
  } catch (err) {
    next(err);
  }
});

router.post('/deadlock/run', async (req, res, next) => {
  let c1;
  let c2;
  try {
    c1 = await getConnection();
    c2 = await getConnection();

    await c1.execute(`UPDATE DEMO_CONCURRENCY_ITEM SET GIA_TRI = GIA_TRI + 1 WHERE ID = 3`);
    await c2.execute(`UPDATE DEMO_CONCURRENCY_ITEM SET GIA_TRI = GIA_TRI + 1 WHERE ID = 4`);

    const results = [];

    try {
      await c1.execute(`SELECT ID FROM DEMO_CONCURRENCY_ITEM WHERE ID = 4 FOR UPDATE NOWAIT`);
      results.push({ session: 'S1', message: 'S1: khóa được dòng B.' });
    } catch (err) {
      results.push({ session: 'S1', message: `S1: chờ dòng B đang bị S2 khóa (${err.message}).` });
    }

    try {
      await c2.execute(`SELECT ID FROM DEMO_CONCURRENCY_ITEM WHERE ID = 3 FOR UPDATE NOWAIT`);
      results.push({ session: 'S2', message: 'S2: khóa được dòng A.' });
    } catch (err) {
      results.push({ session: 'S2', message: `S2: chờ dòng A đang bị S1 khóa (${err.message}).` });
    }

    await c1.rollback();
    await c2.rollback();

    res.json({
      message: 'Đã chạy tình huống hai phiên khóa chéo và rollback dữ liệu demo.',
      details: results.map((item) => item.message),
      snapshot: await getSnapshot()
    });
  } catch (err) {
    try { if (c1) await c1.rollback(); } catch {}
    try { if (c2) await c2.rollback(); } catch {}
    next(err);
  } finally {
    try { if (c1) await c1.close(); } catch {}
    try { if (c2) await c2.close(); } catch {}
  }
});

router.get('/snapshot', async (req, res, next) => {
  try {
    await ensureDemoTables();
    res.json({ snapshot: await getSnapshot() });
  } catch (err) {
    next(err);
  }
});

router.use((err, req, res, next) => {
  res.status(err.status || 500).json({
    message: err.message || 'Lỗi xử lý demo giao tác đồng thời.'
  });
});

export default router;
